# Generated by Django 2.1 on 2018-12-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PMPQuestionBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(choices=[('1', '1st Std'), ('2', '2nd Std'), ('3', '3rd Std'), ('4', '4th Std'), ('5', '5th Std'), ('6', '6th Std'), ('7', '7th Std'), ('8', '8th Std'), ('9', '9th Std'), ('10', '10th Std'), ('11', '11th Std'), ('12', '12th Std')], max_length=10)),
                ('subject', models.CharField(choices=[('E', 'Englist'), ('T', 'Tamil'), ('M', 'Maths'), ('GK', 'GK'), ('SS', 'Social Science'), ('S', 'Science'), ('ES', 'Environmental Science'), ('CS', 'Computer Science'), ('H', 'Hindi')], max_length=10)),
                ('difficulty', models.PositiveIntegerField(choices=[(1, 'Easy'), (2, 'Mid'), (3, 'Tough')])),
                ('marks', models.PositiveIntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')])),
                ('lessonNum', models.PositiveIntegerField(default=1)),
                ('Q_image', models.URLField(blank=True, max_length=1000)),
                ('QuestionType', models.CharField(choices=[('1', 'Choose the best answer'), ('2', 'Choose multiple'), ('3', 'True or False'), ('4', 'Fill in the blanks'), ('5', 'Math')], default=1, max_length=1)),
                ('Question', models.CharField(max_length=1000)),
                ('answer_1', models.CharField(blank=True, max_length=200)),
                ('answer_1_ind', models.BooleanField(default=False)),
                ('answer_2', models.CharField(blank=True, max_length=200)),
                ('answer_2_ind', models.BooleanField(default=False)),
                ('answer_3', models.CharField(blank=True, max_length=200)),
                ('answer_3_ind', models.BooleanField(default=False)),
                ('answer_4', models.CharField(blank=True, max_length=200)),
                ('answer_4_ind', models.BooleanField(default=False)),
                ('answer_5', models.CharField(blank=True, max_length=200)),
                ('answer_5_ind', models.BooleanField(default=False)),
                ('answer_6', models.CharField(blank=True, max_length=200)),
                ('answer_6_ind', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=50)),
                ('userName', models.CharField(blank=True, max_length=50)),
                ('userEmail', models.CharField(blank=True, max_length=50)),
                ('imageUrl', models.CharField(blank=True, max_length=500)),
                ('registeredDate', models.CharField(blank=True, max_length=50)),
                ('loginTime', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=50)),
                ('groupId', models.CharField(blank=True, max_length=20)),
                ('questionSet', models.CharField(blank=True, max_length=500)),
                ('answerSet', models.CharField(blank=True, max_length=500)),
                ('variableSet', models.CharField(blank=True, max_length=500)),
                ('selectedAnsIndex', models.CharField(blank=True, max_length=500)),
                ('score', models.PositiveIntegerField(default=0)),
                ('updatedTime', models.CharField(blank=True, max_length=50)),
                ('quizStatus', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='grouping',
            name='standard',
            field=models.CharField(choices=[('1', '1st Std'), ('2', '2nd Std'), ('3', '3rd Std'), ('4', '4th Std'), ('5', '5th Std'), ('6', '6th Std'), ('7', '7th Std'), ('8', '8th Std'), ('9', '9th Std'), ('10', '10th Std'), ('11', '11th Std'), ('12', '12th Std')], max_length=10),
        ),
        migrations.AlterField(
            model_name='grouping',
            name='subject',
            field=models.CharField(choices=[('E', 'Englist'), ('T', 'Tamil'), ('M', 'Maths'), ('GK', 'GK'), ('SS', 'Social Science'), ('S', 'Science'), ('ES', 'Environmental Science'), ('CS', 'Computer Science'), ('H', 'Hindi')], max_length=10),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='QuestionType',
            field=models.CharField(choices=[('1', 'Choose the best answer'), ('2', 'Choose multiple'), ('3', 'True or False'), ('4', 'Fill in the blanks'), ('5', 'Math')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='marks',
            field=models.PositiveIntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')]),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='standard',
            field=models.CharField(choices=[('1', '1st Std'), ('2', '2nd Std'), ('3', '3rd Std'), ('4', '4th Std'), ('5', '5th Std'), ('6', '6th Std'), ('7', '7th Std'), ('8', '8th Std'), ('9', '9th Std'), ('10', '10th Std'), ('11', '11th Std'), ('12', '12th Std')], max_length=10),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='subject',
            field=models.CharField(choices=[('E', 'Englist'), ('T', 'Tamil'), ('M', 'Maths'), ('GK', 'GK'), ('SS', 'Social Science'), ('S', 'Science'), ('ES', 'Environmental Science'), ('CS', 'Computer Science'), ('H', 'Hindi')], max_length=10),
        ),
    ]
