# Generated by Django 2.1 on 2019-01-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapi', '0003_constants_userpackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouping',
            name='board',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='grouping',
            name='standard',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='grouping',
            name='subject',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pmpquestionbank',
            name='standard',
            field=models.CharField(choices=[('I', 'Initiating'), ('P', 'Planning'), ('E', 'Executing'), ('M', 'Monitoring and Control'), ('C', 'Closing'), ('ET', 'Ethics'), ('G', 'General')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pmpquestionbank',
            name='subject',
            field=models.CharField(choices=[('I', 'Integration'), ('S', 'Scope'), ('T', 'Time'), ('C', 'Cost'), ('Q', 'Quality'), ('H', 'Human Resources'), ('CM', 'Communication'), ('R', 'Risk'), ('P', 'Procurement'), ('ET', 'Ethics'), ('G', 'Generals')], max_length=10),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='standard',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='subject',
            field=models.CharField(max_length=10),
        ),
    ]
