# Generated by Django 2.1 on 2019-03-09 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizapi', '0005_auto_20190126_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='userId',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='userpackage',
            name='userId',
            field=models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to='quizapi.UserDetails', to_field='userId'),
        ),
    ]
