# Generated by Django 2.1 on 2019-03-09 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizapi', '0007_auto_20190309_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquiz',
            name='groupId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapi.Grouping'),
        ),
    ]
