# Generated by Django 2.1 on 2019-03-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapi', '0008_auto_20190309_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquiz',
            name='customId',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
