# Generated by Django 2.1 on 2019-03-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapi', '0009_userquiz_customid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquiz',
            name='customId',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
