# Generated by Django 2.1 on 2019-03-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapi', '0010_auto_20190309_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpackage',
            name='userId',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='userquiz',
            name='groupId',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userquiz',
            name='userId',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
