# Generated by Django 2.1 on 2019-03-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapi', '0011_auto_20190317_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpackage',
            name='userId',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userquiz',
            name='userId',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
