# Generated by Django 2.1 on 2019-03-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapi', '0011_auto_20190317_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpackage',
            name='userId',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userquiz',
            name='userId',
            field=models.CharField(max_length=50),
        ),
    ]
