# Generated by Django 2.1 on 2019-03-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapi', '0012_auto_20190317_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquiz',
            name='userId',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
