# Generated by Django 2.1 on 2019-03-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapi', '0013_auto_20190317_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='userId',
            field=models.CharField(max_length=50),
        ),
    ]
