# Generated by Django 2.1 on 2019-03-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapi', '0014_auto_20190317_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquiz',
            name='customId',
        ),
        migrations.AlterField(
            model_name='userquiz',
            name='groupId',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userquiz',
            name='userId',
            field=models.CharField(max_length=50),
        ),
    ]
