# Generated by Django 2.1 on 2019-07-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapi', '0015_auto_20190317_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('movie', models.CharField(blank=True, max_length=50)),
                ('language', models.CharField(blank=True, max_length=15)),
                ('composer', models.CharField(blank=True, max_length=15)),
                ('imageUrl', models.URLField(blank=True, max_length=1000)),
                ('notes', models.CharField(max_length=10000)),
                ('lyrics', models.CharField(blank=True, max_length=10000)),
                ('localLyrics', models.CharField(blank=True, max_length=10000)),
                ('noteSplit', models.CharField(blank=True, max_length=500)),
                ('sectionSplit', models.CharField(blank=True, max_length=500)),
                ('scale', models.CharField(blank=True, max_length=20)),
                ('raga', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
