# Generated by Django 2.1 on 2019-07-05 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapi', '0016_musicbank'),
        ('quizapi', '0012_auto_20190317_1536'),
    ]

    operations = [
    ]
