# Generated by Django 2.1 on 2019-07-06 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapi', '0017_merge_20190705_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquiz',
            name='customId',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='userId',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
