# Generated by Django 3.1.7 on 2021-03-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapi', '0018_auto_20190706_0822'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
                ('level', models.PositiveIntegerField(default=1)),
                ('section', models.CharField(max_length=30)),
                ('seq_num', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=50)),
                ('contributor', models.CharField(blank=True, max_length=100)),
                ('description_1', models.CharField(blank=True, max_length=1000)),
                ('description_2', models.CharField(blank=True, max_length=1000)),
                ('description_3', models.CharField(blank=True, max_length=1000)),
                ('code_1', models.CharField(blank=True, max_length=2000)),
                ('code_1_type', models.CharField(blank=True, max_length=10)),
                ('code_2', models.CharField(blank=True, max_length=2000)),
                ('code_2_type', models.CharField(blank=True, max_length=10)),
                ('code_3', models.CharField(blank=True, max_length=2000)),
                ('code_3_type', models.CharField(blank=True, max_length=10)),
                ('code_4', models.CharField(blank=True, max_length=2000)),
                ('code_4_type', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
